# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

animal_facts = AniFacts.create([
  {content: 'The first sharks lived more than 400 million years ago—200 million years before the first dinosaurs. They have changed very little over the eons.'},
  {content: 'Unlike dogs, cats do not have a sweet tooth. Scientists believe this is due to a mutation in a key taste receptor.'},
  {content: 'There are approximately 38,000 known species of spiders. Scientists believe there are probably as many more to be discovered.'},
  {content: 'The life span of giant pandas in the wild is approximately 20 years. Captive pandas may live to be 25-30 years old.'},
  {content: 'All dogs can be traced back 40 million years ago to a weasel-like animal called the Miacis which dwelled in trees and dens. The Miacis later evolved into the Tomarctus, a direct forbear of the genus Canis, which includes the wolf and jackal as well as the dog.'},
  {content: 'Sharks belong to a group of fish known as the elasmobranchs, or cartilaginous fishes. Rays and skates, which may have evolved from sharks, also belong to this group.'},
  {content: 'When a cat chases its prey, it keeps its head level. Dogs and humans bob their heads up and down.'},
  {content: 'Spiders are vital to a healthy ecosystem. They eat harmful insects, pollinate plants, and recycle dead animal and plants back into the earth. They are also a valuable food source for many small mammals, birds, and fish.'},
  {content: 'The eyespots of a giant panda cub are initially in the shape of a circle. As the cub grows, the circles become shaped like a teardrop.'},
  {content: 'Small quantities of grapes and raisins can cause renal failure in dogs. Chocolate, macadamia nuts, cooked onions, or anything with caffeine can also be harmful.'},
  {content: 'Because sharks very rarely get cancer, scientists study their cartilage in the hopes of finding a cure for the disease.'},
  {content: 'The technical term for a cat’s hairball is a “bezoar.”'},
  {content: 'The giant panda has been on the endangered species list since 1990. The most significant threats to pandas are habitat loss and poaching. China is only approximately 5% greater than the U.S. in area but has four times the population.'},
  {content: 'Male spiders weave a small “sperm” web. They then place a drop of semen on the web, suck it up with their pedipalps, and then use the pedipalp to insert the sperm into the female.'},
  {content: 'Apple and pear seeds contain arsenic, which may be deadly to dogs.'},
  {content: 'The first written account of a shark attack is found in Herodotus’ (c. 484–425 B.C.) description of hordes of “monsters” devouring the shipwrecked sailors of the Persian fleet.'},
  {content: 'A group of cats is called a “clowder.”'},
  {content: 'Pandas have been a symbol of peace in China. For example, hundreds of years ago, warring tribes in China would raise a flag with a picture of a panda on it to stop a battle or call a truce.'},
  {content: 'Dogs have sweat glands in between their paws.'},
  {content: 'While blood likely does not provoke a shark to attack, a shark in the vicinity likely can detect the blood. Without any conclusive proof of how sharks might respond, some scientists suggest women stay out of the water while menstruating.'},
  {content: 'A cat can’t climb head first down a tree because every claw on a cat’s paw points the same way. To get down from a tree, a cat must back down.'},
  {content: 'The Bagheera kiplingi is the world’s only (mostly) vegetarian spider.'},
  {content: 'Giant pandas are on the brink of extinction, with just over 1,000 pandas left in the world. Scientists are hoping to increase the wild panda population to 5,000 by 2025.'},
  {content: 'Giant pandas are on the brink of extinction, with just over 1,000 pandas left in the world. Scientists are hoping to increase the wild panda population to 5,000 by 2025.'},
  {content: 'In 2003, Dr. Roger Mugford invented the “wagometer,” a device that claims to interpret a dog’s exact mood by measuring the wag of its tail.'},
  {content: 'When a shark eats food that it can’t digest (like a turtle shell or tin can), it can vomit by thrusting its stomach out its mouth then pulling it back in.'},
  {content: 'Cats make about 100 different sounds. Dogs make only about 10.'},
  {content: 'The red panda and the giant panda share the same habitat and diet, and both animals are also endangered. However, scientific tests show that the red panda is in the raccoon family while the giant panda is in the bear family. Some scientists believe that the giant panda is so special that it should belong to its own family group.'},
  {content: 'In rare instances, some spider bites can cause blood disorders. For example, the brown recluse venom may cause red blood cells to burst. This can lead to other symptoms, such as acute kidney injury and jaundice.'},
  {content: 'Ancient Egyptians revered their dogs. When a pet dog would die, the owners shaved off their eyebrows, smeared mud in their hair, and mourned aloud for days.'},
  {content: 'A shark’s jaw is not attached to its cranium. Because its mouth is situated on the underside of its head, a shark can temporarily dislocate its jaw and jut it forward to take a bite.'},
  {content: 'Every year, nearly four million cats are eaten in Asia.'},
  {content: 'According to legend, the panda was once an all-white bear. When a small girl tried to save a panda cub from being attacked by a leopard, the leopard killed the girl instead. Pandas came to her funeral wearing armbands of black ashes. As they wiped their eyes, hugged each other, and covered the ears, they smudged the black ashes.'},
  {content: 'The venom of the black widow spider attacks nerves by blocking their signals to the muscles, which causes the muscles to contract repeatedly and often painfully. Black widow bites can also cause other nerve-related problems, such as high blood pressure, restlessness, and severe facial spasms.'},
  {content: 'Dogs have three eyelids. The third lid, called a nictitating membrane or “haw,” keeps the eye lubricated and protected.'},
  {content: 'Before sandpaper was invented, people used the rough skin of sharks, called shagreen, to smooth and polish wood. Japanese warriors wrapped the skin around the handles of their swords to keep the swords from slipping out of their hands.'},
  {content: 'There are more than 500 million domestic cats in the world, with approximately 40 recognized breeds.'},
  {content: 'Pandas can stand upright, but their short hind legs aren’t strong enough to support their bodies. A panda’s bones are twice as heavy as the bones of other animals the same size.'},
  {content: 'A dog’s shoulder blades are unattached to the rest of the skeleton to allow greater flexibility for running.'},
  {content: 'The first pup to hatch inside the sand tiger shark mother devours its brothers and sisters until there are only two pups left, one on each side of the womb. This form of cannibalism is called oophagy.'},
  {content: 'Approximately 24 cat skins can make a coat.'},
  {content: 'Pandas are pigeon-toed; in other words, they walk with their front paws turned inward.'},
  {content: 'Puppies are sometimes rejected by their mother if they are born by cesarean and cleaned up before being given back to her.'},
  {content: 'The first use of the word “shark” in English occurred in 1569. Previously, English sailors and fishermen used the term “sea dog” or the Spanish tiburón. It could possibly be from the German Schorck, which is a variant of Schurke (“scoundrel villain”) from shürgen (“to poke, stir”).'},
  {content: 'While it is commonly thought that the ancient Egyptians were the first to domesticate cats, the oldest known pet cat was recently found in a 9,500-year-old grave on the Mediterranean island of Cyprus. This grave predates early Egyptian art depicting cats by 4,000 years or more.'},
  {content: 'Pandas do not run fast—a slow trot is as fast as they can go. The fastest bear is the black bear, which can run 35 miles per hour. That’s about as a fast as a horse or deer.'},
  {content: 'The phrase “raining cats and dogs” originated in seventeenth-century England. During heavy rainstorms, many homeless animals would drown and float down the streets, giving the appearance that it had actually rained cats and dogs.'},
  {content: 'The most deadly spiders in the world include the black widow, funnel web, and brown recluse spiders. One of the most feared spiders in the world, the tarantula, actually has surprisingly weak venom and a bite that feels more like a wasp sting.'},
  {content: 'Jellyfish are found in every ocean of the world. They are even found in some freshwater lakes and ponds.'},
  {content: 'During the time of the Spanish Inquisition, Pope Innocent VIII condemned cats as evil and thousands of cats were burned. Unfortunately, the widespread killing of cats led to an explosion of the rat population, which exacerbated the effects of the Black Death.'},
  {content: 'Pandas rely less on visual memory than they do on spatial memory to locate a mate’s home range area and preferred patches of bamboo. Spatial memory is defined as the ability to remember a location.'},
  {content: 'During the Middle Ages, Great Danes and Mastiffs were sometimes suited with armor and spiked collars to enter a battle or to defend supply caravans.'},
  {content: 'Jellyfish range from the size of a thimble or the eraser tip of pencil to approximately eight feet in diameter with tentacles that reach 200 feet. That is as long as two blue whales.'},
  {content: 'During the Middle Ages, cats were associated with withcraft, and on St. John’s Day, people all over Europe would stuff them into sacks and toss the cats into bonfires. On holy days, people celebrated by tossing cats from church towers.'},
  {content: 'Many Chinese philosophers believe that the universe is made from two opposing forces, the Yin and Yang. The panda is one symbol of this philosophy with its contrasting black-and-white fur. The Chinese believe that the gentle nature of the panda demonstrates how the Yin and Yang bring peace and harmony when they are balanced.'},
  {content: 'Pekingese and Japanese Chins were so important in the ancient Far East that they had their own servants and were carried around trade routes as gifts for kings and emperors. Pekingese were even worshipped in the temples of China for centuries.'},
  {content: 'The most venomous spider in the world is the Brazilian Wandering Spider, or the banana spider. This aggressive spider wanders the forest floors of Central and South America looking for food. Just a small amount of venom is enough to kill a human.'},
  {content: 'Each jellyfish tentacle is armed with thousands of cells called cnidoblasts. Inside the cnidoblasts are nematocysts, each of which contains a coiled stinging thread. When a fish or other object becomes tangled in the tentacles, the pressure inside the nematocysts causes the venomous threads to uncoil like a spring-loaded harpoon.'},
  {content: 'The first cat in space was a French cat named Felicette (a.k.a. “Astrocat”) In 1963, France blasted the cat into outer space. Electrodes implanted in her brains sent neurological signals back to Earth. She survived the trip.'},
  {content: 'Female pandas ovulate only once a year. They are fertile only two or three days of the year.'},
  {content: 'While humans have muscles on the outside of their skeleton, spiders have muscles on the inside. A spider’s skeleton, or exoskeleton, covers and protects its muscles.'},
  {content: 'After the fall of Rome, human survival often became more important than breeding and training dogs. Legends of werewolves emerged during this time as abandoned dogs traveling in packs commonly roamed streets and terrified villagers.'},
  {content: 'The jellyfish’s main defense mechanisms are its stings and its transparent body, which makes it easy for it to hide.'},
  {content: 'The group of words associated with cat (catt, cath, chat, katze) stem from the Latin catus, meaning domestic cat, as opposed to feles, or wild cat.'},
  {content: 'It takes about five years for a female cub to become an adult and up to seven years for a male cub.'},
  {content: 'In tropical regions, net-throwing spiders make a small silken web that they throw over their prey.'},
  {content: 'The most dogs ever owned by one person were 5,000 Mastiffs owned by Kublai Khan.'},
  {content: 'The Portuguese man-of-war looks like a jellyfish, but it is not a true jellyfish. In fact, it is not even a single animal. It is a siphonophore, which is an animal made up of a colony of organisms that work together. Specifically, the man-of-war consists of four separate polyps. The top polyp is a gas-filled bladder that reminded people of the sails on a once common ship called a man-of-war.'},
  {content: 'The term “puss” is the root of the principal word for “cat” in the Romanian term pisica and the root of secondary words in Lithuanian (puz) and Low German puus. Some scholars suggest that “puss” could be imitative of the hissing sound used to get a cat’s attention. As a slang word for the female pudenda, it could be associated with the connotation of a cat being soft, warm, and fuzzy.'},
  {content: 'Some male spiders give dead flies to the females as presents.'},
  {content: 'There are only about 240 captive pandas in the world. They are all part of a breeding program.'},
  {content: 'The American Kennel Club, the most influential dog club in the United States, was founded in 1884.'},
  {content: 'Jellyfish live from a few hours to many months. One species has been reported to live as long as 30 years. Jellyfish in aquariums typically live longer than those in the wild. Because jellyfish are so fragile, it’s easier for people to capture jellyfish in the polyp stage when they are the least vulnerable.'},
  {content: 'Approximately 40,000 people are bitten by cats in the U.S. annually.'},
  {content: 'The ancestor of the giant panda is the Ailurarctos (“cat bear”), which is an extinct genus of the Chinese panda that lived 8 million years ago. The skull of another ancestor, Ailuropoda microta, shows that it was half the size of a modern-day giant panda. Research shows that for the past 3 million years, giant pandas have evolved as a separate linage from other bears.'},
  {content: 'The most popular male dog names are Max and Jake. The most popular female dog names are Maggie and Molly.'},
  {content: 'One species of jellyfish, the Turritopsis nutricula, is also known as the “immortal jellyfish” because it can transform from the mature medusa state back to the polyp state, thereby essentially avoiding death. It accomplishes this through the cell development process called transdifferentiation.'},
  {content: 'Cats are North America’s most popular pets: there are 73 million cats compared to 63 million dogs. Over 30% of households in North America own a cat.'},
  {content: 'Pandas have plantigrade feet. This means their entire foot (toes and heel) touches the ground when walking, which is similar to the way humans, other bears, and rodents walk. Other animals, such as dogs, cats, and horses walk with their weight on their toes.'},
  {content: 'Weird dog laws include allowing police offers in Palding, Ohio, to bite a dog to quiet it. In Ventura County, California, cats and dogs are not allowed to have sex without a permit.'},
  {content: 'The type of jellyfish most seen on the shores of North America and Europe is the Moon jellyfish. This type of jellyfish is typically blue or pink and is found in waters approximately 20 feet (6 meters) deep. Its sting is usually mild, but can leave an itchy, red rash.'},
  {content: 'According to Hebrew legend, Noah prayed to God for help protecting all the food he stored on the ark from being eaten by rats. In reply, God made the lion sneeze, and out popped a cat.'},
  {content: 'Mother pandas in captivity give birth to twins more often than mothers in the wild do.'},
  {content: 'When a wheel spider gets scared, it tucks in its legs and rolls across the sand.'},
  {content: 'The first dog chapel was established in 2001. It was built in St. Johnsbury, Vermont, by Stephan Huneck, a children’s book author whose five dogs helped him recuperate from a serious illness.'},
  {content: 'There are more than 2,000 different types of jellyfish. Approximately 70 can hurt people, with the box jellyfish (Chironex fleckeri) being the most dangerous. Scientists believe that there could be as many as 300,000 different species of jellyfish yet to be discovered.'},
  {content: 'A cat’s hearing is better than a dog’s. And a cat can hear high-frequency sounds up to two octaves higher than a human.'},
  {content: 'More than half of newborn pandas die from diseases or from being accidentally crushed by their mothers.'},
  {content: 'Those born under the sign of the dog in Chinese astrology are considered to be loyal and discreet, though slightly temperamental.'},
  {content: 'Environmental stress may increase jellyfish swarms. Jellyfish are one of the very few creatures that can adapt to ocean dead zones, or zones where there is little oxygen and lots of pollution. There are over 400 marine dead zones in the world.'},
  {content: 'A cat can travel at a top speed of approximately 31 mph (49 km) over a short distance.'},
  {content: 'From 1974-1989, half of the panda’s habitat in China’s Sichuan areas was destroyed by human activity.'},
  {content: 'In Iran, it is against the law to own a dog as a pet. However, if an owner can prove the dog is a guard or hunting dog, this restriction doesn’t apply. Muslim reticence concerning dogs is perhaps due to the fact that rabies has always been endemic in the Middle East.'},
  {content: 'Approximately 150 million people annually are exposed to jellyfish around the globe. Around 200,000 people are stung each year in Florida and 500,000 around the Chesapeake Bay.'},
  {content: 'A cat rubs against people not only to be affectionate but also to mark out its territory with scent glands around its face. The tail area and paws also carry the cat’s scent.'},
  {content: 'Giant panda cubs are usually born in August or September and are the size of a stick of butter. A cub has pink skin, a thin coat of white fur, a long tail, and no teeth. Its eyes are closed. By the end of the first month, the baby panda has all of its spots. Its eyes open around 4-6 weeks. A baby panda is almost 2 months old before it is the size of an average human newborn baby. A baby is almost 2 years old when it leaves its mother.'},
  {content: 'Jellyfish are harvested for collagen, which is used in a variety ways, including treating rheumatoid arthritis.'},
  {content: 'The Mayans and Aztecs symbolized every tenth day with the dog, and those born under this sign were believed to have outstanding leadership skills.'},
  {content: 'Researchers are unsure exactly how a cat purrs. Most veterinarians believe that a cat purrs by vibrating vocal folds deep in the throat. To do this, a muscle in the larynx opens and closes the air passage about 25 times per second.'},
  {content: 'A pair of breeding pandas needs more than 11 square miles of land. One giant panda usually needs between 2.5 to 4 square miles of land to survive.'},
  {content: 'An adult jellyfish is named a “medusa” (plural “medusae”), after the Greek monster Medusa that had snake for hair.'},
  {content: 'The shape of a dog’s face suggests how long it will live. Dogs with sharp, pointed faces that look more like wolves typically live longer. Dogs with very flat faces, such as bulldogs, often have shorter lives.'},
  {content: 'When a family cat died in ancient Egypt, family members would mourn by shaving off their eyebrows. They also held elaborate funerals during which they drank wine and beat their breasts. The cat was embalmed with a sculpted wooden mask and the tiny mummy was placed in the family tomb or in a pet cemetery with tiny mummies of mice.'},
  {content: 'A panda fur is worth between $60,000 and $100,000 on the illegal trade market.'},
  {content: 'Most jellyfish have two basic life stages. In the first stage, they are called polyps and grow by making buds, like plants. The polyp then buds off a young jellyfish called an ephyra. After a few weeks, the ephyra becomes an adult jellyfish or medusa.'},
  {content: 'The ancient Mbaya Indians of the Gran Chaco in South America believed that humans originally lived underground until dogs dug them up.'},
  {content: 'In 1888, more than 300,000 mummified cats were found an Egyptian cemetery. They were stripped of their wrappings and carted off to be used by farmers in England and the U.S. for fertilizer.'},
  {content: 'A red widow female spider will begin feeding on the male while they are still mating. However, the male practically force feeds himself to the female by placing himself into her mandibles. If she “spits him out,” he will repeatedly place himself there until she eats him.'},
  ])
